<div class="col-md-6 col-lg-6 col-sm-6 col-xs-12 mix " style="margin-top: 20px">
            <div class="portfolio-item">
              <div class="portfolio-img" >
                <img src="[field:img/]" alt="" style="padding: 10px" /> 
              </div>
              <div class="portfoli-content">
                <div class="sup-desc-wrap">
                  <div class="sup-desc-inner">
                    <div class="sup-meta-wrap">
                      <a class="sup-title" href="#">
                        <h4>[field:title/]</h4>
                      </a>
                      <p class="sup-description">[field:des/]</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>